import json
import os

# 250 Countries and Territories dataset matching REST Countries API v3.1 schema
raw_countries = [
    # Europe
    ("DEU", "Germany", "Federal Republic of Germany", ["Berlin"], "Europe", "Western Europe", 83240525, "de", [".de"], {"EUR": ("Euro", "€")}, {"deu": "German"}, ["AUT", "BEL", "CZE", "DNK", "FRA", "LUX", "NLD", "POL", "CHE"]),
    ("FRA", "France", "French Republic", ["Paris"], "Europe", "Western Europe", 67391582, "fr", [".fr"], {"EUR": ("Euro", "€")}, {"fra": "French"}, ["AND", "BEL", "DEU", "ITA", "LUX", "MCO", "ESP", "CHE"]),
    ("GBR", "United Kingdom", "United Kingdom of Great Britain and Northern Ireland", ["London"], "Europe", "Northern Europe", 67215293, "gb", [".uk"], {"GBP": ("British pound", "£")}, {"eng": "English"}, ["IRL"]),
    ("ITA", "Italy", "Italian Republic", ["Rome"], "Europe", "Southern Europe", 59554023, "it", [".it"], {"EUR": ("Euro", "€")}, {"ita": "Italian"}, ["AUT", "FRA", "SMR", "SVN", "CHE", "VAT"]),
    ("ESP", "Spain", "Kingdom of Spain", ["Madrid"], "Europe", "Southern Europe", 47351567, "es", [".es"], {"EUR": ("Euro", "€")}, {"spa": "Spanish"}, ["AND", "FRA", "GIB", "PRT", "MAR"]),
    ("NLD", "Netherlands", "Kingdom of the Netherlands", ["Amsterdam"], "Europe", "Western Europe", 17441139, "nl", [".nl"], {"EUR": ("Euro", "€")}, {"nld": "Dutch"}, ["BEL", "DEU"]),
    ("BEL", "Belgium", "Kingdom of Belgium", ["Brussels"], "Europe", "Western Europe", 11555997, "be", [".be"], {"EUR": ("Euro", "€")}, {"nld": "Dutch", "fra": "French", "deu": "German"}, ["FRA", "DEU", "LUX", "NLD"]),
    ("CHE", "Switzerland", "Swiss Confederation", ["Bern"], "Europe", "Western Europe", 8654622, "ch", [".ch"], {"CHF": ("Swiss franc", "CHF")}, {"fra": "French", "gsw": "Swiss German", "ita": "Italian", "roh": "Romansh"}, ["AUT", "FRA", "DEU", "ITA", "LIE"]),
    ("AUT", "Austria", "Republic of Austria", ["Vienna"], "Europe", "Central Europe", 8917205, "at", [".at"], {"EUR": ("Euro", "€")}, {"deu": "German"}, ["CZE", "DEU", "HUN", "ITA", "LIE", "SVK", "SVN", "CHE"]),
    ("PRT", "Portugal", "Portuguese Republic", ["Lisbon"], "Europe", "Southern Europe", 10305564, "pt", [".pt"], {"EUR": ("Euro", "€")}, {"por": "Portuguese"}, ["ESP"]),
    ("SWE", "Sweden", "Kingdom of Sweden", ["Stockholm"], "Europe", "Northern Europe", 10353442, "se", [".se"], {"SEK": ("Swedish krona", "kr")}, {"swe": "Swedish"}, ["FIN", "NOR"]),
    ("NOR", "Norway", "Kingdom of Norway", ["Oslo"], "Europe", "Northern Europe", 5379475, "no", [".no"], {"NOK": ("Norwegian krone", "kr")}, {"nno": "Nynorsk", "nob": "Bokmål", "smi": "Sami"}, ["FIN", "SWE", "RUS"]),
    ("DNK", "Denmark", "Kingdom of Denmark", ["Copenhagen"], "Europe", "Northern Europe", 5831404, "dk", [".dk"], {"DKK": ("Danish krone", "kr")}, {"dan": "Danish"}, ["DEU"]),
    ("FIN", "Finland", "Republic of Finland", ["Helsinki"], "Europe", "Northern Europe", 5530719, "fi", [".fi"], {"EUR": ("Euro", "€")}, {"fin": "Finnish", "swe": "Swedish"}, ["NOR", "SWE", "RUS"]),
    ("POL", "Poland", "Republic of Poland", ["Warsaw"], "Europe", "Central Europe", 37950802, "pl", [".pl"], {"PLN": ("Polish złoty", "zł")}, {"pol": "Polish"}, ["BLR", "CZE", "DEU", "LTU", "RUS", "SVK", "UKR"]),
    ("CZE", "Czechia", "Czech Republic", ["Prague"], "Europe", "Central Europe", 10698896, "cz", [".cz"], {"CZK": ("Czech koruna", "Kč")}, {"ces": "Czech", "slk": "Slovak"}, ["AUT", "DEU", "POL", "SVK"]),
    ("HUN", "Hungary", "Hungary", ["Budapest"], "Europe", "Central Europe", 9749763, "hu", [".hu"], {"HUF": ("Hungarian forint", "Ft")}, {"hun": "Hungarian"}, ["AUT", "HRV", "ROU", "SRB", "SVK", "SVN", "UKR"]),
    ("GRC", "Greece", "Hellenic Republic", ["Athens"], "Europe", "Southern Europe", 10715549, "gr", [".gr"], {"EUR": ("Euro", "€")}, {"ell": "Greek"}, ["ALB", "BGR", "TUR", "MKD"]),
    ("ROU", "Romania", "Romania", ["Bucharest"], "Europe", "Southeast Europe", 19286123, "ro", [".ro"], {"RON": ("Romanian leu", "lei")}, {"ron": "Romanian"}, ["BGR", "HUN", "MDA", "SRB", "UKR"]),
    ("BGR", "Bulgaria", "Republic of Bulgaria", ["Sofia"], "Europe", "Southeast Europe", 6927288, "bg", [".bg"], {"BGN": ("Bulgarian lev", "лв")}, {"bul": "Bulgarian"}, ["GRC", "MKD", "ROU", "SRB", "TUR"]),
    ("IRL", "Ireland", "Republic of Ireland", ["Dublin"], "Europe", "Northern Europe", 4994724, "ie", [".ie"], {"EUR": ("Euro", "€")}, {"eng": "English", "gle": "Irish"}, ["GBR"]),
    ("SVK", "Slovakia", "Slovak Republic", ["Bratislava"], "Europe", "Central Europe", 5458827, "sk", [".sk"], {"EUR": ("Euro", "€")}, {"slk": "Slovak"}, ["AUT", "CZE", "HUN", "POL", "UKR"]),
    ("HRV", "Croatia", "Republic of Croatia", ["Zagreb"], "Europe", "Southeast Europe", 4047200, "hr", [".hr"], {"EUR": ("Euro", "€")}, {"hrv": "Croatian"}, ["BIH", "HUN", "MNE", "SRB", "SVN"]),
    ("SRB", "Serbia", "Republic of Serbia", ["Belgrade"], "Europe", "Southeast Europe", 6908224, "rs", [".rs"], {"RSD": ("Serbian dinar", "din.")}, {"srb": "Serbian"}, ["BIH", "BGR", "HRV", "HUN", "KOS", "MKD", "MNE", "ROU"]),
    ("SVN", "Slovenia", "Republic of Slovenia", ["Ljubljana"], "Europe", "Central Europe", 2100126, "si", [".si"], {"EUR": ("Euro", "€")}, {"slv": "Slovene"}, ["AUT", "HRV", "ITA", "HUN"]),
    ("LTU", "Lithuania", "Republic of Lithuania", ["Vilnius"], "Europe", "Northern Europe", 2794700, "lt", [".lt"], {"EUR": ("Euro", "€")}, {"lit": "Lithuanian"}, ["BLR", "LVA", "POL", "RUS"]),
    ("LVA", "Latvia", "Republic of Latvia", ["Riga"], "Europe", "Northern Europe", 1901548, "lv", [".lv"], {"EUR": ("Euro", "€")}, {"lav": "Latvian"}, ["BLR", "EST", "LTU", "RUS"]),
    ("EST", "Estonia", "Republic of Estonia", ["Tallinn"], "Europe", "Northern Europe", 1331057, "ee", [".ee"], {"EUR": ("Euro", "€")}, {"est": "Estonian"}, ["LVA", "RUS"]),
    ("BLR", "Belarus", "Republic of Belarus", ["Minsk"], "Europe", "Eastern Europe", 9398861, "by", [".by"], {"BYN": ("Belarusian ruble", "Br")}, {"bel": "Belarusian", "rus": "Russian"}, ["LVA", "LTU", "POL", "RUS", "UKR"]),
    ("UKR", "Ukraine", "Ukraine", ["Kyiv"], "Europe", "Eastern Europe", 44134693, "ua", [".ua"], {"UAH": ("Ukrainian hryvnia", "₴")}, {"ukr": "Ukrainian"}, ["BLR", "HUN", "MDA", "POL", "ROU", "RUS", "SVK"]),
    ("MDA", "Moldova", "Republic of Moldova", ["Chișinău"], "Europe", "Eastern Europe", 2617820, "md", [".md"], {"MDL": ("Moldovan leu", "L")}, {"ron": "Romanian"}, ["ROU", "UKR"]),
    ("ALB", "Albania", "Republic of Albania", ["Tirana"], "Europe", "Southeast Europe", 2837743, "al", [".al"], {"ALL": ("Albanian lek", "L")}, {"sqi": "Albanian"}, ["MNE", "GRC", "MKD", "KOS"]),
    ("MKD", "North Macedonia", "Republic of North Macedonia", ["Skopje"], "Europe", "Southeast Europe", 2077132, "mk", [".mk"], {"MKD": ("denar", "den")}, {"mkd": "Macedonian"}, ["ALB", "BGR", "GRC", "KOS", "SRB"]),
    ("MNE", "Montenegro", "Montenegro", ["Podgorica"], "Europe", "Southeast Europe", 621718, "me", [".me"], {"EUR": ("Euro", "€")}, {"cnr": "Montenegrin"}, ["ALB", "BIH", "HRV", "KOS", "SRB"]),
    ("BIH", "Bosnia and Herzegovina", "Bosnia and Herzegovina", ["Sarajevo"], "Europe", "Southeast Europe", 3280815, "ba", [".ba"], {"BAM": ("Convertible mark", "KM")}, {"bos": "Bosnian", "hrv": "Croatian", "srb": "Serbian"}, ["HRV", "MNE", "SRB"]),
    ("KOS", "Kosovo", "Republic of Kosovo", ["Pristina"], "Europe", "Southeast Europe", 1800000, "xk", [".xk"], {"EUR": ("Euro", "€")}, {"sqi": "Albanian", "srb": "Serbian"}, ["ALB", "MKD", "MNE", "SRB"]),
    ("ISL", "Iceland", "Iceland", ["Reykjavík"], "Europe", "Northern Europe", 366425, "is", [".is"], {"ISK": ("Icelandic króna", "kr")}, {"isl": "Icelandic"}, []),
    ("LUX", "Luxembourg", "Grand Duchy of Luxembourg", ["Luxembourg"], "Europe", "Western Europe", 632275, "lu", [".lu"], {"EUR": ("Euro", "€")}, {"deu": "German", "fra": "French", "ltz": "Luxembourgish"}, ["BEL", "FRA", "DEU"]),
    ("MLT", "Malta", "Republic of Malta", ["Valletta"], "Europe", "Southern Europe", 525285, "mt", [".mt"], {"EUR": ("Euro", "€")}, {"eng": "English", "mlt": "Maltese"}, []),
    ("CYP", "Cyprus", "Republic of Cyprus", ["Nicosia"], "Europe", "Southern Europe", 1207359, "cy", [".cy"], {"EUR": ("Euro", "€")}, {"ell": "Greek", "tur": "Turkish"}, ["GBR"]),
    ("AND", "Andorra", "Principality of Andorra", ["Andorra la Vella"], "Europe", "Southern Europe", 77265, "ad", [".ad"], {"EUR": ("Euro", "€")}, {"cat": "Catalan"}, ["FRA", "ESP"]),
    ("MCO", "Monaco", "Principality of Monaco", ["Monaco"], "Europe", "Western Europe", 39242, "mc", [".mc"], {"EUR": ("Euro", "€")}, {"fra": "French"}, ["FRA"]),
    ("LIE", "Liechtenstein", "Principality of Liechtenstein", ["Vaduz"], "Europe", "Western Europe", 38128, "li", [".li"], {"CHF": ("Swiss franc", "CHF")}, {"deu": "German"}, ["AUT", "CHE"]),
    ("SMR", "San Marino", "Republic of San Marino", ["City of San Marino"], "Europe", "Southern Europe", 33931, "sm", [".sm"], {"EUR": ("Euro", "€")}, {"ita": "Italian"}, ["ITA"]),
    ("VAT", "Vatican City", "Vatican City State", ["Vatican City"], "Europe", "Southern Europe", 825, "va", [".va"], {"EUR": ("Euro", "€")}, {"ita": "Italian", "lat": "Latin"}, ["ITA"]),
    ("FRO", "Faroe Islands", "Faroe Islands", ["Tórshavn"], "Europe", "Northern Europe", 48865, "fo", [".fo"], {"DKK": ("Danish krone", "kr"), "FOK": ("Faroese króna", "kr")}, {"fao": "Faroese"}, []),
    ("GIB", "Gibraltar", "Gibraltar", ["Gibraltar"], "Europe", "Southern Europe", 33691, "gi", [".gi"], {"GIP": ("Gibraltar pound", "£")}, {"eng": "English"}, ["ESP"]),
    ("GGY", "Guernsey", "Bailiwick of Guernsey", ["St. Peter Port"], "Europe", "Northern Europe", 63124, "gg", [".gg"], {"GBP": ("British pound", "£"), "GGP": ("Guernsey pound", "£")}, {"eng": "English", "nrf": "Guernésiais"}, []),
    ("JEY", "Jersey", "Bailiwick of Jersey", ["Saint Helier"], "Europe", "Northern Europe", 107800, "je", [".je"], {"GBP": ("British pound", "£"), "JEP": ("Jersey pound", "£")}, {"eng": "English", "nrf": "Jèrriais"}, []),
    ("IMN", "Isle of Man", "Isle of Man", ["Douglas"], "Europe", "Northern Europe", 85033, "im", [".im"], {"GBP": ("British pound", "£"), "IMP": ("Manx pound", "£")}, {"eng": "English", "glv": "Manx"}, []),
    ("SJM", "Svalbard and Jan Mayen", "Svalbard og Jan Mayen", ["Longyearbyen"], "Europe", "Northern Europe", 2562, "sj", [".sj"], {"NOK": ("Norwegian krone", "kr")}, {"nor": "Norwegian"}, []),
    ("ALA", "Åland Islands", "Åland Islands", ["Mariehamn"], "Europe", "Northern Europe", 29458, "ax", [".ax"], {"EUR": ("Euro", "€")}, {"swe": "Swedish"}, []),
    ("GRL", "Greenland", "Greenland", ["Nuuk"], "Americas", "North America", 56367, "gl", [".gl"], {"DKK": ("Danish krone", "kr")}, {"kal": "Greenlandic"}, []),
    ("RUS", "Russia", "Russian Federation", ["Moscow"], "Europe", "Eastern Europe", 144104080, "ru", [".ru"], {"RUB": ("Russian ruble", "₽")}, {"rus": "Russian"}, ["AZE", "BLR", "CHN", "EST", "FIN", "GEO", "KAZ", "PRK", "LVA", "LTU", "MNG", "NOR", "POL", "UKR"]),

    # Americas
    ("USA", "United States", "United States of America", ["Washington, D.C."], "Americas", "North America", 329484123, "us", [".us"], {"USD": ("United States dollar", "$")}, {"eng": "English"}, ["CAN", "MEX"]),
    ("CAN", "Canada", "Canada", ["Ottawa"], "Americas", "North America", 38005238, "ca", [".ca"], {"CAD": ("Canadian dollar", "$")}, {"eng": "English", "fra": "French"}, ["USA"]),
    ("MEX", "Mexico", "United Mexican States", ["Mexico City"], "Americas", "North America", 128932753, "mx", [".mx"], {"MXN": ("Mexican peso", "$")}, {"spa": "Spanish"}, ["BLZ", "GTM", "USA"]),
    ("GTM", "Guatemala", "Republic of Guatemala", ["Guatemala City"], "Americas", "Central America", 16858333, "gt", [".gt"], {"GTQ": ("Guatemalan quetzal", "Q")}, {"spa": "Spanish"}, ["BLZ", "SLV", "HND", "MEX"]),
    ("BLZ", "Belize", "Belize", ["Belmopan"], "Americas", "Central America", 397621, "bz", [".bz"], {"BZD": ("Belize dollar", "$")}, {"eng": "English", "bjz": "Belizean Creole", "spa": "Spanish"}, ["GTM", "MEX"]),
    ("SLV", "El Salvador", "Republic of El Salvador", ["San Salvador"], "Americas", "Central America", 6486201, "sv", [".sv"], {"USD": ("United States dollar", "$")}, {"spa": "Spanish"}, ["GTM", "HND"]),
    ("HND", "Honduras", "Republic of Honduras", ["Tegucigalpa"], "Americas", "Central America", 9904608, "hn", [".hn"], {"HNL": ("Honduran lempira", "L")}, {"spa": "Spanish"}, ["GTM", "NIC", "SLV"]),
    ("NIC", "Nicaragua", "Republic of Nicaragua", ["Managua"], "Americas", "Central America", 6624554, "ni", [".ni"], {"NIO": ("Nicaraguan córdoba", "C$")}, {"spa": "Spanish"}, ["CRI", "HND"]),
    ("CRI", "Costa Rica", "Republic of Costa Rica", ["San José"], "Americas", "Central America", 5094114, "cr", [".cr"], {"CRC": ("Costa Rican colón", "₡")}, {"spa": "Spanish"}, ["NIC", "PAN"]),
    ("PAN", "Panama", "Republic of Panama", ["Panama City"], "Americas", "Central America", 4314768, "pa", [".pa"], {"PAB": ("Panamanian balboa", "B/."), "USD": ("United States dollar", "$")}, {"spa": "Spanish"}, ["COL", "CRI"]),
    ("COL", "Colombia", "Republic of Colombia", ["Bogotá"], "Americas", "South America", 50882884, "co", [".co"], {"COP": ("Colombian peso", "$")}, {"spa": "Spanish"}, ["BRA", "ECU", "PAN", "PER", "VEN"]),
    ("VEN", "Venezuela", "Bolivarian Republic of Venezuela", ["Caracas"], "Americas", "South America", 28435943, "ve", [".ve"], {"VES": ("Sovereign bolívar", "Bs.S.")}, {"spa": "Spanish"}, ["BRA", "COL", "GUY"]),
    ("GUY", "Guyana", "Co-operative Republic of Guyana", ["Georgetown"], "Americas", "South America", 786559, "gy", [".gy"], {"GYD": ("Guyanese dollar", "$")}, {"eng": "English"}, ["BRA", "SUR", "VEN"]),
    ("SUR", "Suriname", "Republic of Suriname", ["Paramaribo"], "Americas", "South America", 586634, "sr", [".sr"], {"SRD": ("Surinamese dollar", "$")}, {"nld": "Dutch"}, ["BRA", "GUY", "GUF"]),
    ("ECU", "Ecuador", "Republic of Ecuador", ["Quito"], "Americas", "South America", 17643060, "ec", [".ec"], {"USD": ("United States dollar", "$")}, {"spa": "Spanish"}, ["COL", "PER"]),
    ("PER", "Peru", "Republic of Peru", ["Lima"], "Americas", "South America", 32971846, "pe", [".pe"], {"PEN": ("Sol", "S/.")}, {"aym": "Aymara", "que": "Quechua", "spa": "Spanish"}, ["BOL", "BRA", "CHL", "COL", "ECU"]),
    ("BRA", "Brazil", "Federative Republic of Brazil", ["Brasília"], "Americas", "South America", 212559409, "br", [".br"], {"BRL": ("Brazilian real", "R$")}, {"por": "Portuguese"}, ["ARG", "BOL", "COL", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"]),
    ("BOL", "Bolivia", "Plurinational State of Bolivia", ["Sucre"], "Americas", "South America", 11673029, "bo", [".bo"], {"BOB": ("Bolivian boliviano", "Bs.")}, {"aym": "Aymara", "grn": "Guaraní", "que": "Quechua", "spa": "Spanish"}, ["ARG", "BRA", "CHL", "PRY", "PER"]),
    ("PRY", "Paraguay", "Republic of Paraguay", ["Asunción"], "Americas", "South America", 7132530, "py", [".py"], {"PYG": ("Paraguayan guaraní", "₲")}, {"grn": "Guaraní", "spa": "Spanish"}, ["ARG", "BOL", "BRA"]),
    ("CHL", "Chile", "Republic of Chile", ["Santiago"], "Americas", "South America", 19116209, "cl", [".cl"], {"CLP": ("Chilean peso", "$")}, {"spa": "Spanish"}, ["ARG", "BOL", "PER"]),
    ("ARG", "Argentina", "Argentine Republic", ["Buenos Aires"], "Americas", "South America", 45376763, "ar", [".ar"], {"ARS": ("Argentine peso", "$")}, {"spa": "Spanish"}, ["BOL", "BRA", "CHL", "PRY", "URY"]),
    ("URY", "Uruguay", "Oriental Republic of Uruguay", ["Montevideo"], "Americas", "South America", 3473727, "uy", [".uy"], {"UYU": ("Uruguayan peso", "$")}, {"spa": "Spanish"}, ["ARG", "BRA"]),
    ("CUB", "Cuba", "Republic of Cuba", ["Havana"], "Americas", "Caribbean", 11326616, "cu", [".cu"], {"CUP": ("Cuban peso", "$")}, {"spa": "Spanish"}, []),
    ("HTI", "Haiti", "Republic of Haiti", ["Port-au-Prince"], "Americas", "Caribbean", 11402533, "ht", [".ht"], {"HTG": ("Haitian gourde", "G")}, {"fra": "French", "hat": "Haitian Creole"}, ["DOM"]),
    ("DOM", "Dominican Republic", "Dominican Republic", ["Santo Domingo"], "Americas", "Caribbean", 10847904, "do", [".do"], {"DOP": ("Dominican peso", "RD$")}, {"spa": "Spanish"}, ["HTI"]),
    ("JAM", "Jamaica", "Jamaica", ["Kingston"], "Americas", "Caribbean", 2961161, "jm", [".jm"], {"JMD": ("Jamaican dollar", "$")}, {"eng": "English"}, []),
    ("BHS", "Bahamas", "Commonwealth of the Bahamas", ["Nassau"], "Americas", "Caribbean", 393248, "bs", [".bs"], {"BSD": ("Bahamian dollar", "$")}, {"eng": "English"}, []),
    ("BRB", "Barbados", "Barbados", ["Bridgetown"], "Americas", "Caribbean", 287371, "bb", [".bb"], {"BBD": ("Barbadian dollar", "$")}, {"eng": "English"}, []),
    ("TTO", "Trinidad and Tobago", "Republic of Trinidad and Tobago", ["Port of Spain"], "Americas", "Caribbean", 1399491, "tt", [".tt"], {"TTD": ("Trinidad and Tobago dollar", "TT$")}, {"eng": "English"}, []),
    ("KNA", "Saint Kitts and Nevis", "Federation of Saint Christopher and Nevis", ["Basseterre"], "Americas", "Caribbean", 53192, "kn", [".kn"], {"XCD": ("East Caribbean dollar", "$")}, {"eng": "English"}, []),
    ("LCA", "Saint Lucia", "Saint Lucia", ["Castries"], "Americas", "Caribbean", 183629, "lc", [".lc"], {"XCD": ("East Caribbean dollar", "$")}, {"eng": "English"}, []),
    ("VCT", "Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines", ["Kingstown"], "Americas", "Caribbean", 110947, "vc", [".vc"], {"XCD": ("East Caribbean dollar", "$")}, {"eng": "English"}, []),
    ("ATG", "Antigua and Barbuda", "Antigua and Barbuda", ["St. John's"], "Americas", "Caribbean", 97928, "ag", [".ag"], {"XCD": ("East Caribbean dollar", "$")}, {"eng": "English"}, []),
    ("DMA", "Dominica", "Commonwealth of Dominica", ["Roseau"], "Americas", "Caribbean", 71991, "dm", [".dm"], {"XCD": ("East Caribbean dollar", "$")}, {"eng": "English"}, []),
    ("GRD", "Grenada", "Grenada", ["St. George's"], "Americas", "Caribbean", 112519, "gd", [".gd"], {"XCD": ("East Caribbean dollar", "$")}, {"eng": "English"}, []),
    ("PRI", "Puerto Rico", "Commonwealth of Puerto Rico", ["San Juan"], "Americas", "Caribbean", 3194034, "pr", [".pr"], {"USD": ("United States dollar", "$")}, {"eng": "English", "spa": "Spanish"}, []),
    ("CYM", "Cayman Islands", "Cayman Islands", ["George Town"], "Americas", "Caribbean", 65720, "ky", [".ky"], {"KYD": ("Cayman Islands dollar", "$")}, {"eng": "English"}, []),
    ("BMU", "Bermuda", "Bermuda", ["Hamilton"], "Americas", "North America", 63903, "bm", [".bm"], {"BMD": ("Bermudian dollar", "$")}, {"eng": "English"}, []),
    ("ABW", "Aruba", "Aruba", ["Oranjestad"], "Americas", "Caribbean", 106766, "aw", [".aw"], {"AWG": ("Aruban florin", "ƒ")}, {"nld": "Dutch", "pap": "Papiamento"}, []),
    ("CUW", "Curaçao", "Country of Curaçao", ["Willemstad"], "Americas", "Caribbean", 155014, "cw", [".cw"], {"ANG": ("Netherlands Antillean guilder", "ƒ")}, {"eng": "English", "nld": "Dutch", "pap": "Papiamento"}, []),
    ("SXM", "Sint Maarten", "Sint Maarten", ["Philipsburg"], "Americas", "Caribbean", 42848, "sx", [".sx"], {"ANG": ("Netherlands Antillean guilder", "ƒ")}, {"eng": "English", "nld": "Dutch"}, []),
    ("AIA", "Anguilla", "Anguilla", ["The Valley"], "Americas", "Caribbean", 15002, "ai", [".ai"], {"XCD": ("East Caribbean dollar", "$")}, {"eng": "English"}, []),
    ("MSR", "Montserrat", "Montserrat", ["Plymouth"], "Americas", "Caribbean", 4992, "ms", [".ms"], {"XCD": ("East Caribbean dollar", "$")}, {"eng": "English"}, []),
    ("VGB", "Virgin Islands (British)", "Virgin Islands", ["Road Town"], "Americas", "Caribbean", 30237, "vg", [".vg"], {"USD": ("United States dollar", "$")}, {"eng": "English"}, []),
    ("VIR", "Virgin Islands (U.S.)", "Virgin Islands of the United States", ["Charlotte Amalie"], "Americas", "Caribbean", 106290, "vi", [".vi"], {"USD": ("United States dollar", "$")}, {"eng": "English"}, []),
    ("TCA", "Turks and Caicos Islands", "Turks and Caicos Islands", ["Cockburn Town"], "Americas", "Caribbean", 38718, "tc", [".tc"], {"USD": ("United States dollar", "$")}, {"eng": "English"}, []),
    ("SPM", "Saint Pierre and Miquelon", "Saint Pierre and Miquelon", ["Saint-Pierre"], "Americas", "North America", 6008, "pm", [".pm"], {"EUR": ("Euro", "€")}, {"fra": "French"}, []),
    ("GLP", "Guadeloupe", "Guadeloupe", ["Basse-Terre"], "Americas", "Caribbean", 395700, "gp", [".gp"], {"EUR": ("Euro", "€")}, {"fra": "French"}, []),
    ("MTQ", "Martinique", "Martinique", ["Fort-de-France"], "Americas", "Caribbean", 376480, "mq", [".mq"], {"EUR": ("Euro", "€")}, {"fra": "French"}, []),
    ("MAF", "Saint Martin", "Saint Martin", ["Marigot"], "Americas", "Caribbean", 38659, "mf", [".mf"], {"EUR": ("Euro", "€")}, {"fra": "French"}, ["SXM"]),
    ("BLM", "Saint Barthélemy", "Collectivity of Saint Barthélemy", ["Gustavia"], "Americas", "Caribbean", 9961, "bl", [".bl"], {"EUR": ("Euro", "€")}, {"fra": "French"}, []),
    ("BES", "Bonaire, Sint Eustatius and Saba", "Bonaire, Sint Eustatius and Saba", ["Kralendijk"], "Americas", "Caribbean", 25987, "bq", [".bq"], {"USD": ("United States dollar", "$")}, {"nld": "Dutch", "pap": "Papiamento"}, []),
    ("FLK", "Falkland Islands", "Falkland Islands", ["Stanley"], "Americas", "South America", 3480, "fk", [".fk"], {"FKP": ("Falkland Islands pound", "£")}, {"eng": "English"}, []),
    ("GUF", "French Guiana", "French Guiana", ["Cayenne"], "Americas", "South America", 294071, "gf", [".gf"], {"EUR": ("Euro", "€")}, {"fra": "French"}, ["BRA", "SUR"]),
    ("UMI", "United States Minor Outlying Islands", "United States Minor Outlying Islands", ["Washington D.C."], "Americas", "North America", 300, "um", [".um"], {"USD": ("United States dollar", "$")}, {"eng": "English"}, []),

    # Asia
    ("CHN", "China", "People's Republic of China", ["Beijing"], "Asia", "Eastern Asia", 1402112000, "cn", [".cn"], {"CNY": ("Chinese yuan", "¥")}, {"zho": "Chinese"}, ["AFG", "BTN", "IND", "KAZ", "KGZ", "LAO", "MNG", "MMR", "NPL", "PRK", "PAK", "RUS", "TJK", "VNM"]),
    ("JPN", "Japan", "Japan", ["Tokyo"], "Asia", "Eastern Asia", 125836021, "jp", [".jp"], {"JPY": ("Japanese yen", "¥")}, {"jpn": "Japanese"}, []),
    ("IND", "India", "Republic of India", ["New Delhi"], "Asia", "Southern Asia", 1380004385, "in", [".in"], {"INR": ("Indian rupee", "₹")}, {"eng": "English", "hin": "Hindi"}, ["BGD", "BTN", "MMR", "CHN", "NPL", "PAK"]),
    ("IDN", "Indonesia", "Republic of Indonesia", ["Jakarta"], "Asia", "South-Eastern Asia", 273523621, "id", [".id"], {"IDR": ("Indonesian rupiah", "Rp")}, {"ind": "Indonesian"}, ["TLS", "MYS", "PNG"]),
    ("PAK", "Pakistan", "Islamic Republic of Pakistan", ["Islamabad"], "Asia", "Southern Asia", 220892331, "pk", [".pk"], {"PKR": ("Pakistani rupee", "₨")}, {"eng": "English", "urd": "Urdu"}, ["AFG", "CHN", "IND", "IRN"]),
    ("BGD", "Bangladesh", "People's Republic of Bangladesh", ["Dhaka"], "Asia", "Southern Asia", 164689383, "bd", [".bd"], {"BDT": ("Bangladeshi taka", "৳")}, {"ben": "Bengali"}, ["MMR", "IND"]),
    ("KOR", "South Korea", "Republic of Korea", ["Seoul"], "Asia", "Eastern Asia", 51780579, "kr", [".kr"], {"KRW": ("South Korean won", "₩")}, {"kor": "Korean"}, ["PRK"]),
    ("PRK", "North Korea", "Democratic People's Republic of Korea", ["Pyongyang"], "Asia", "Eastern Asia", 25778815, "kp", [".kp"], {"KPW": ("North Korean won", "₩")}, {"kor": "Korean"}, ["CHN", "KOR", "RUS"]),
    ("VNM", "Vietnam", "Socialist Republic of Vietnam", ["Hanoi"], "Asia", "South-Eastern Asia", 97338583, "vn", [".vn"], {"VND": ("Vietnamese đồng", "₫")}, {"vie": "Vietnamese"}, ["KHM", "CHN", "LAO"]),
    ("PHL", "Philippines", "Republic of the Philippines", ["Manila"], "Asia", "South-Eastern Asia", 109581085, "ph", [".ph"], {"PHP": ("Philippine peso", "₱")}, {"eng": "English", "fil": "Filipino"}, []),
    ("THA", "Thailand", "Kingdom of Thailand", ["Bangkok"], "Asia", "South-Eastern Asia", 69799978, "th", [".th"], {"THB": ("Thai baht", "฿")}, {"tha": "Thai"}, ["KHM", "LAO", "MYS", "MMR"]),
    ("MYS", "Malaysia", "Malaysia", ["Kuala Lumpur"], "Asia", "South-Eastern Asia", 32365998, "my", [".my"], {"MYR": ("Malaysian ringgit", "RM")}, {"msa": "Malay"}, ["BRN", "IDN", "THA"]),
    ("SGP", "Singapore", "Republic of Singapore", ["Singapore"], "Asia", "South-Eastern Asia", 5685807, "sg", [".sg"], {"SGD": ("Singapore dollar", "$")}, {"zho": "Chinese", "eng": "English", "msa": "Malay", "tam": "Tamil"}, []),
    ("MMR", "Myanmar", "Republic of the Union of Myanmar", ["Naypyidaw"], "Asia", "South-Eastern Asia", 54409794, "mm", [".mm"], {"MMK": ("Burmese kyat", "Ks")}, {"myan": "Burmese"}, ["BGD", "CHN", "IND", "LAO", "THA"]),
    ("KHM", "Cambodia", "Kingdom of Cambodia", ["Phnom Penh"], "Asia", "South-Eastern Asia", 16718971, "kh", [".kh"], {"KHR": ("Cambodian riel", "៛"), "USD": ("United States dollar", "$")}, {"khm": "Khmer"}, ["LAO", "THA", "VNM"]),
    ("LAO", "Laos", "Lao People's Democratic Republic", ["Vientiane"], "Asia", "South-Eastern Asia", 7275556, "la", [".la"], {"LAK": ("Lao kip", "₭")}, {"lao": "Lao"}, ["KHM", "CHN", "MMR", "THA", "VNM"]),
    ("NPL", "Nepal", "Federal Democratic Republic of Nepal", ["Kathmandu"], "Asia", "Southern Asia", 29136808, "np", [".np"], {"NPR": ("Nepalese rupee", "₨")}, {"nep": "Nepali"}, ["CHN", "IND"]),
    ("LKA", "Sri Lanka", "Democratic Socialist Republic of Sri Lanka", ["Sri Jayawardenepura Kotte"], "Asia", "Southern Asia", 21919000, "lk", [".lk"], {"LKR": ("Sri Lankan rupee", "Rs")}, {"sin": "Sinhala", "tam": "Tamil"}, ["IND"]),
    ("AFG", "Afghanistan", "Islamic Republic of Afghanistan", ["Kabul"], "Asia", "Southern Asia", 38928341, "af", [".af"], {"AFN": ("Afghan afghani", "؋")}, {"prs": "Dari", "pus": "Pashto", "tuk": "Turkmen"}, ["CHN", "IRN", "PAK", "TJK", "TKM", "UZB"]),
    ("IRN", "Iran", "Islamic Republic of Iran", ["Tehran"], "Asia", "Southern Asia", 83992953, "ir", [".ir"], {"IRR": ("Iranian rial", "﷼")}, {"fas": "Persian"}, ["AFG", "ARM", "AZE", "IRQ", "PAK", "TUR", "TKM"]),
    ("IRQ", "Iraq", "Republic of Iraq", ["Baghdad"], "Asia", "Western Asia", 40222503, "iq", [".iq"], {"IQD": ("Iraqi dinar", "ع.د")}, {"ara": "Arabic", "kur": "Kurdish"}, ["IRN", "JOR", "KWT", "SAU", "SYR", "TUR"]),
    ("SAU", "Saudi Arabia", "Kingdom of Saudi Arabia", ["Riyadh"], "Asia", "Western Asia", 34813867, "sa", [".sa"], {"SAR": ("Saudi riyal", "ر.س")}, {"ara": "Arabic"}, ["IRQ", "JOR", "KWT", "OMN", "QAT", "ARE", "YEM"]),
    ("YEM", "Yemen", "Republic of Yemen", ["Sana'a"], "Asia", "Western Asia", 29825968, "ye", [".ye"], {"YER": ("Yemeni rial", "﷼")}, {"ara": "Arabic"}, ["OMN", "SAU"]),
    ("OMN", "Oman", "Sultanate of Oman", ["Muscat"], "Asia", "Western Asia", 5106622, "om", [".om"], {"OMR": ("Omani rial", "ر.ع.")}, {"ara": "Arabic"}, ["SAU", "ARE", "YEM"]),
    ("ARE", "United Arab Emirates", "United Arab Emirates", ["Abu Dhabi"], "Asia", "Western Asia", 9890400, "ae", [".ae"], {"AED": ("United Arab Emirates dirham", "د.إ")}, {"ara": "Arabic"}, ["OMN", "SAU"]),
    ("QAT", "Qatar", "State of Qatar", ["Doha"], "Asia", "Western Asia", 2881060, "qa", [".qa"], {"QAR": ("Qatari riyal", "ر.ق")}, {"ara": "Arabic"}, ["SAU"]),
    ("KWT", "Kuwait", "State of Kuwait", ["Kuwait City"], "Asia", "Western Asia", 4270563, "kw", [".kw"], {"KWD": ("Kuwaiti dinar", "د.ك")}, {"ara": "Arabic"}, ["IRQ", "SAU"]),
    ("BHR", "Bahrain", "Kingdom of Bahrain", ["Manama"], "Asia", "Western Asia", 1701583, "bh", [".bh"], {"BHD": ("Bahraini dinar", ".د.ب")}, {"ara": "Arabic"}, []),
    ("JOR", "Jordan", "Hashemite Kingdom of Jordan", ["Amman"], "Asia", "Western Asia", 10203140, "jo", [".jo"], {"JOD": ("Jordanian dinar", "د.ا")}, {"ara": "Arabic"}, ["IRQ", "ISR", "SAU", "SYR", "PSE"]),
    ("LBN", "Lebanon", "Lebanese Republic", ["Beirut"], "Asia", "Western Asia", 6825442, "lb", [".lb"], {"LBP": ("Lebanese pound", "ل.ل")}, {"ara": "Arabic"}, ["ISR", "SYR"]),
    ("SYR", "Syria", "Syrian Arab Republic", ["Damascus"], "Asia", "Western Asia", 17500657, "sy", [".sy"], {"SYP": ("Syrian pound", "ل.س")}, {"ara": "Arabic"}, ["IRQ", "ISR", "JOR", "LBN", "TUR"]),
    ("ISR", "Israel", "State of Israel", ["Jerusalem"], "Asia", "Western Asia", 9216900, "il", [".il"], {"ILS": ("Israeli new shekel", "₪")}, {"ara": "Arabic", "heb": "Hebrew"}, ["EGY", "JOR", "LBN", "PSE", "SYR"]),
    ("PSE", "Palestine", "State of Palestine", ["Ramallah"], "Asia", "Western Asia", 4803269, "ps", [".ps"], {"EGP": ("Egyptian pound", "E£"), "ILS": ("Israeli new shekel", "₪"), "JOD": ("Jordanian dinar", "JD")}, {"ara": "Arabic"}, ["EGY", "ISR", "JOR"]),
    ("TUR", "Turkey", "Republic of Turkey", ["Ankara"], "Asia", "Western Asia", 84339067, "tr", [".tr"], {"TRY": ("Turkish lira", "₺")}, {"tur": "Turkish"}, ["ARM", "AZE", "BGR", "GEO", "GRC", "IRN", "IRQ", "SYR"]),
    ("GEO", "Georgia", "Georgia", ["Tbilisi"], "Asia", "Western Asia", 3714000, "ge", [".ge"], {"GEL": ("Lari", "₾")}, {"kat": "Georgian"}, ["ARM", "AZE", "RUS", "TUR"]),
    ("ARM", "Armenia", "Republic of Armenia", ["Yerevan"], "Asia", "Western Asia", 2963234, "am", [".am"], {"AMD": ("Armenian dram", "֏")}, {"hyw": "Armenian"}, ["AZE", "GEO", "IRN", "TUR"]),
    ("AZE", "Azerbaijan", "Republic of Azerbaijan", ["Baku"], "Asia", "Western Asia", 10110116, "az", [".az"], {"AZN": ("Azerbaijani manat", "₼")}, {"aze": "Azerbaijani"}, ["ARM", "GEO", "IRN", "RUS", "TUR"]),
    ("KAZ", "Kazakhstan", "Republic of Kazakhstan", ["Nur-Sultan"], "Asia", "Central Asia", 18754440, "kz", [".kz"], {"KZT": ("Kazakhstani tenge", "₸")}, {"kaz": "Kazakh", "rus": "Russian"}, ["CHN", "KGZ", "RUS", "TKM", "UZB"]),
    ("UZB", "Uzbekistan", "Republic of Uzbekistan", ["Tashkent"], "Asia", "Central Asia", 34232050, "uz", [".uz"], {"UZS": ("Uzbekistani soʻm", "so'm")}, {"rus": "Russian", "uzb": "Uzbek"}, ["AFG", "KAZ", "KGZ", "TJK", "TKM"]),
    ("TKM", "Turkmenistan", "Turkmenistan", ["Ashgabat"], "Asia", "Central Asia", 6031187, "tm", [".tm"], {"TMT": ("Turkmenistan manat", "m")}, {"rus": "Russian", "tuk": "Turkmen"}, ["AFG", "IRN", "KAZ", "UZB"]),
    ("KGZ", "Kyrgyzstan", "Kyrgyz Republic", ["Bishkek"], "Asia", "Central Asia", 6591600, "kg", [".kg"], {"KGS": ("Kyrgyzstani som", "сом")}, {"kir": "Kyrgyz", "rus": "Russian"}, ["CHN", "KAZ", "TJK", "UZB"]),
    ("TJK", "Tajikistan", "Republic of Tajikistan", ["Dushanbe"], "Asia", "Central Asia", 9537642, "tj", [".tj"], {"TJS": ("Tajikistani somoni", "ЅМ")}, {"tgk": "Tajik"}, ["AFG", "CHN", "KGZ", "UZB"]),
    ("MNG", "Mongolia", "Mongolia", ["Ulaanbaatar"], "Asia", "Eastern Asia", 3278290, "mn", [".mn"], {"MNT": ("Mongolian tögrög", "₮")}, {"mon": "Mongolian"}, ["CHN", "RUS"]),
    ("TWN", "Taiwan", "Republic of China (Taiwan)", ["Taipei"], "Asia", "Eastern Asia", 23568378, "tw", [".tw"], {"TWD": ("New Taiwan dollar", "NT$")}, {"zho": "Traditional Chinese"}, []),
    ("HKG", "Hong Kong", "Hong Kong Special Administrative Region of the People's Republic of China", ["City of Victoria"], "Asia", "Eastern Asia", 7500700, "hk", [".hk"], {"HKD": ("Hong Kong dollar", "$")}, {"eng": "English", "zho": "Chinese"}, ["CHN"]),
    ("MAC", "Macau", "Macao Special Administrative Region of the People's Republic of China", ["Macau"], "Asia", "Eastern Asia", 683218, "mo", [".mo"], {"MOP": ("Macanese pataca", "P")}, {"por": "Portuguese", "zho": "Chinese"}, ["CHN"]),
    ("MDV", "Maldives", "Republic of Maldives", ["Malé"], "Asia", "Southern Asia", 540542, "mv", [".mv"], {"MVR": ("Maldivian rufiyaa", "Rf")}, {"div": "Dhivehi"}, []),
    ("BTN", "Bhutan", "Kingdom of Bhutan", ["Thimphu"], "Asia", "Southern Asia", 771612, "bt", [".bt"], {"BTN": ("Bhutanese ngultrum", "Nu."), "INR": ("Indian rupee", "₹")}, {"dzo": "Dzongkha"}, ["CHN", "IND"]),
    ("TLS", "Timor-Leste", "Democratic Republic of Timor-Leste", ["Dili"], "Asia", "South-Eastern Asia", 1318442, "tl", [".tl"], {"USD": ("United States dollar", "$")}, {"por": "Portuguese", "tet": "Tetum"}, ["IDN"]),
    ("BRN", "Brunei", "Nation of Brunei, Abode of Peace", ["Bandar Seri Begawan"], "Asia", "South-Eastern Asia", 437483, "bn", [".bn"], {"BND": ("Brunei dollar", "$"), "SGD": ("Singapore dollar", "$")}, {"msa": "Malay"}, ["MYS"]),

    # Africa
    ("NGA", "Nigeria", "Federal Republic of Nigeria", ["Abuja"], "Africa", "Western Africa", 206139587, "ng", [".ng"], {"NGN": ("Nigerian naira", "₦")}, {"eng": "English"}, ["BEN", "CMR", "TCD", "NER"]),
    ("ETH", "Ethiopia", "Federal Democratic Republic of Ethiopia", ["Addis Ababa"], "Africa", "Eastern Africa", 114963583, "et", [".et"], {"ETB": ("Ethiopian birr", "Br")}, {"amh": "Amharic"}, ["DJI", "ERI", "KEN", "SOM", "SSD", "SDN"]),
    ("EGY", "Egypt", "Arab Republic of Egypt", ["Cairo"], "Africa", "Northern Africa", 102334403, "eg", [".eg"], {"EGP": ("Egyptian pound", "E£")}, {"ara": "Arabic"}, ["ISR", "LBY", "PSE", "SDN"]),
    ("COD", "DR Congo", "Democratic Republic of the Congo", ["Kinshasa"], "Africa", "Middle Africa", 89561404, "cd", [".cd"], {"CDF": ("Congolese franc", "FC")}, {"fra": "French", "kon": "Kikongo", "lin": "Lingala", "lua": "Tshiluba", "swa": "Swahili"}, ["AGO", "BDI", "CAF", "COG", "RWA", "SSD", "TZA", "UGA", "ZMB"]),
    ("ZAF", "South Africa", "Republic of South Africa", ["Pretoria"], "Africa", "Southern Africa", 59308690, "za", [".za"], {"ZAR": ("South African rand", "R")}, {"afr": "Afrikaans", "eng": "English", "nbl": "Southern Ndebele", "nso": "Northern Sotho", "sot": "Southern Sotho", "ssw": "Swati", "tsn": "Tswana", "tso": "Tsonga", "ven": "Venda", "xho": "Xhosa", "zul": "Zulu"}, ["BWA", "LSO", "MOZ", "NAM", "SWZ", "ZWE"]),
    ("TZA", "Tanzania", "United Republic of Tanzania", ["Dodoma"], "Africa", "Eastern Africa", 59734213, "tz", [".tz"], {"TZS": ("Tanzanian shilling", "Sh")}, {"eng": "English", "swa": "Swahili"}, ["BDI", "COD", "KEN", "MWI", "MOZ", "RWA", "UGA", "ZMB"]),
    ("SDN", "Sudan", "Republic of the Sudan", ["Khartoum"], "Africa", "Northern Africa", 43849269, "sd", [".sd"], {"SDG": ("Sudanese pound", "SDG")}, {"ara": "Arabic", "eng": "English"}, ["CAF", "TCD", "EGY", "ERI", "ETH", "LBY", "SSD"]),
    ("DZA", "Algeria", "People's Democratic Republic of Algeria", ["Algiers"], "Africa", "Northern Africa", 44700000, "dz", [".dz"], {"DZD": ("Algerian dinar", "د.ج")}, {"ara": "Arabic"}, ["TUN", "LBY", "NER", "ESH", "MRT", "MLI", "MAR"]),
    ("MAR", "Morocco", "Kingdom of Morocco", ["Rabat"], "Africa", "Northern Africa", 36910558, "ma", [".ma"], {"MAD": ("Moroccan dirham", "د.م.")}, {"ara": "Arabic", "ber": "Berber"}, ["DZA", "ESP", "ESH"]),
    ("AGO", "Angola", "Republic of Angola", ["Luanda"], "Africa", "Middle Africa", 32866268, "ao", [".ao"], {"AOA": ("Angolan kwanza", "Kz")}, {"por": "Portuguese"}, ["COD", "COG", "NAM", "ZMB"]),
    ("GHA", "Ghana", "Republic of Ghana", ["Accra"], "Africa", "Western Africa", 31072945, "gh", [".gh"], {"GHS": ("Ghanaian cedi", "₵")}, {"eng": "English"}, ["BFA", "CIV", "TGO"]),
    ("MOZ", "Mozambique", "Republic of Mozambique", ["Maputo"], "Africa", "Eastern Africa", 31255435, "mz", [".mz"], {"MZN": ("Mozambican metical", "MT")}, {"por": "Portuguese"}, ["SWZ", "MWI", "ZAF", "TZA", "ZMB", "ZWE"]),
    ("MDG", "Madagascar", "Republic of Madagascar", ["Antananarivo"], "Africa", "Eastern Africa", 27691019, "mg", [".mg"], {"MGA": ("Malagasy ariary", "Ar")}, {"fra": "French", "mlg": "Malagasy"}, []),
    ("CIV", "Ivory Coast", "Republic of Côte d'Ivoire", ["Yamoussoukro"], "Africa", "Western Africa", 26378275, "ci", [".ci"], {"XOF": ("West African CFA franc", "CFA")}, {"fra": "French"}, ["BFA", "GHA", "GIN", "LBR", "MLI"]),
    ("CMR", "Cameroon", "Republic of Cameroon", ["Yaoundé"], "Africa", "Middle Africa", 26545864, "cm", [".cm"], {"XAF": ("Central African CFA franc", "FCFA")}, {"eng": "English", "fra": "French"}, ["CAF", "TCD", "COG", "GNQ", "GAB", "NGA"]),
    ("NER", "Niger", "Republic of Niger", ["Niamey"], "Africa", "Western Africa", 24206636, "ne", [".ne"], {"XOF": ("West African CFA franc", "CFA")}, {"fra": "French"}, ["DZA", "BEN", "TCD", "LBY", "MLI", "NGA", "BFA"]),
    ("BFA", "Burkina Faso", "Burkina Faso", ["Ouagadougou"], "Africa", "Western Africa", 20903278, "bf", [".bf"], {"XOF": ("West African CFA franc", "CFA")}, {"fra": "French"}, ["BEN", "CIV", "GHA", "MLI", "NER", "TGO"]),
    ("MLI", "Mali", "Republic of Mali", ["Bamako"], "Africa", "Western Africa", 20250834, "ml", [".ml"], {"XOF": ("West African CFA franc", "CFA")}, {"fra": "French"}, ["DZA", "BFA", "CIV", "GIN", "MRT", "NER", "SEN"]),
    ("MWI", "Malawi", "Republic of Malawi", ["Lilongwe"], "Africa", "Eastern Africa", 19129955, "mw", [".mw"], {"MWK": ("Malawian kwacha", "MK")}, {"eng": "English", "nya": "Chichewa"}, ["MOZ", "TZA", "ZMB"]),
    ("ZMB", "Zambia", "Republic of Zambia", ["Lusaka"], "Africa", "Eastern Africa", 18383956, "zm", [".zm"], {"ZMW": ("Zambian kwacha", "ZK")}, {"eng": "English"}, ["AGO", "BWA", "COD", "MWI", "MOZ", "NAM", "TZA", "ZWE"]),
    ("SOM", "Somalia", "Federal Republic of Somalia", ["Mogadishu"], "Africa", "Eastern Africa", 15893219, "so", [".so"], {"SOS": ("Somali shilling", "Sh")}, {"ara": "Arabic", "som": "Somali"}, ["DJI", "ETH", "KEN"]),
    ("SEN", "Senegal", "Republic of Senegal", ["Dakar"], "Africa", "Western Africa", 16743930, "sn", [".sn"], {"XOF": ("West African CFA franc", "CFA")}, {"fra": "French"}, ["GMB", "GIN", "GNB", "MLI", "MRT"]),
    ("TCD", "Chad", "Republic of Chad", ["N'Djamena"], "Africa", "Middle Africa", 16425859, "td", [".td"], {"XAF": ("Central African CFA franc", "FCFA")}, {"ara": "Arabic", "fra": "French"}, ["CMR", "CAF", "LBY", "NER", "NGA", "SDN"]),
    ("ZWE", "Zimbabwe", "Republic of Zimbabwe", ["Harare"], "Africa", "Eastern Africa", 14862927, "zw", [".zw"], {"ZWL": ("Zimbabwean dollar", "$")}, {"bwj": "Bwisi", "eng": "English", "kck": "Kalanga", "khi": "Khoekhoe", "ndc": "Ndau", "nde": "Northern Ndebele", "nya": "Chichewa", "sna": "Shona", "sot": "Sotho", "toi": "Tonga", "tsn": "Tswana", "tso": "Tsonga", "ven": "Venda", "xho": "Xhosa"}, ["BWA", "MOZ", "ZAF", "ZMB"]),
    ("GIN", "Guinea", "Republic of Guinea", ["Conakry"], "Africa", "Western Africa", 13132792, "gn", [".gn"], {"GNF": ("Guinean franc", "FG")}, {"fra": "French"}, ["CIV", "GNB", "LBR", "MLI", "SEN", "SLE"]),
    ("RWA", "Rwanda", "Republic of Rwanda", ["Kigali"], "Africa", "Eastern Africa", 12952209, "rw", [".rw"], {"RWF": ("Rwandan franc", "FRw")}, {"eng": "English", "fra": "French", "kin": "Kinyarwanda"}, ["BDI", "COD", "TZA", "UGA"]),
    ("BEN", "Benin", "Republic of Benin", ["Porto-Novo"], "Africa", "Western Africa", 12123198, "bj", [".bj"], {"XOF": ("West African CFA franc", "CFA")}, {"fra": "French"}, ["BFA", "NER", "NGA", "TGO"]),
    ("BDI", "Burundi", "Republic of Burundi", ["Gitega"], "Africa", "Eastern Africa", 11890781, "bi", [".bi"], {"BIF": ("Burundian franc", "FBu")}, {"fra": "French", "run": "Kirundi"}, ["COD", "RWA", "TZA"]),
    ("TUN", "Tunisia", "Republic of Tunisia", ["Tunis"], "Africa", "Northern Africa", 11818618, "tn", [".tn"], {"TND": ("Tunisian dinar", "د.ت")}, {"ara": "Arabic"}, ["DZA", "LBY"]),
    ("SSD", "South Sudan", "Republic of South Sudan", ["Juba"], "Africa", "Eastern Africa", 11193729, "ss", [".ss"], {"SSP": ("South Sudanese pound", "£")}, {"eng": "English"}, ["CAF", "COD", "ETH", "KEN", "SDN", "UGA"]),
    ("TGO", "Togo", "Togolese Republic", ["Lomé"], "Africa", "Western Africa", 8278737, "tg", [".tg"], {"XOF": ("West African CFA franc", "CFA")}, {"fra": "French"}, ["BEN", "BFA", "GHA"]),
    ("SLE", "Sierra Leone", "Republic of Sierra Leone", ["Freetown"], "Africa", "Western Africa", 7976985, "sl", [".sl"], {"SLL": ("Sierra Leonean leone", "Le")}, {"eng": "English"}, ["GIN", "LBR"]),
    ("LBR", "Liberia", "Republic of Liberia", ["Monrovia"], "Africa", "Western Africa", 5057677, "lr", [".lr"], {"LRD": ("Liberian dollar", "$")}, {"eng": "English"}, ["CIV", "GIN", "SLE"]),
    ("CAF", "Central African Republic", "Central African Republic", ["Bangui"], "Africa", "Middle Africa", 4829764, "cf", [".cf"], {"XAF": ("Central African CFA franc", "FCFA")}, {"fra": "French", "sag": "Sango"}, ["CMR", "TCD", "COD", "COG", "SSD", "SDN"]),
    ("MRT", "Mauritania", "Islamic Republic of Mauritania", ["Nouakchott"], "Africa", "Western Africa", 4649660, "mr", [".mr"], {"MRU": ("Mauritanian ouguiya", "UM")}, {"ara": "Arabic"}, ["DZA", "MLI", "SEN", "ESH"]),
    ("COG", "Republic of the Congo", "Republic of the Congo", ["Brazzaville"], "Africa", "Middle Africa", 5518092, "cg", [".cg"], {"XAF": ("Central African CFA franc", "FCFA")}, {"fra": "French", "kon": "Kikongo", "lin": "Lingala"}, ["AGO", "CMR", "CAF", "COD", "GAB"]),
    ("ERI", "Eritrea", "State of Eritrea", ["Asmara"], "Africa", "Eastern Africa", 3546427, "er", [".er"], {"ERN": ("Eritrean nakfa", "Nfk")}, {"ara": "Arabic", "eng": "English", "tir": "Tigrinya"}, ["DJI", "ETH", "SDN"]),
    ("NAM", "Namibia", "Republic of Namibia", ["Windhoek"], "Africa", "Southern Africa", 2540916, "na", [".na"], {"NAD": ("Namibian dollar", "$"), "ZAR": ("South African rand", "R")}, {"afr": "Afrikaans", "eng": "English", "her": "Herero", "hgm": "Nama", "kwn": "Kwangali", "loz": "Lozi", "ndo": "Ndonga", "tsn": "Tswana"}, ["AGO", "BWA", "ZAF", "ZMB"]),
    ("GMB", "Gambia", "Republic of the Gambia", ["Banjul"], "Africa", "Western Africa", 2416664, "gm", [".gm"], {"GMD": ("Gambian dalasi", "D")}, {"eng": "English"}, ["SEN"]),
    ("BWA", "Botswana", "Republic of Botswana", ["Gaborone"], "Africa", "Southern Africa", 2351625, "bw", [".bw"], {"BWP": ("Botswana pula", "P")}, {"eng": "English", "tsn": "Tswana"}, ["NAM", "ZAF", "ZMB", "ZWE"]),
    ("GNB", "Guinea-Bissau", "Republic of Guinea-Bissau", ["Bissau"], "Africa", "Western Africa", 1968003, "gw", [".gw"], {"XOF": ("West African CFA franc", "CFA")}, {"por": "Portuguese"}, ["GIN", "SEN"]),
    ("LSO", "Lesotho", "Kingdom of Lesotho", ["Maseru"], "Africa", "Southern Africa", 2142252, "ls", [".ls"], {"LSL": ("Lesotho loti", "L"), "ZAR": ("South African rand", "R")}, {"eng": "English", "sot": "Sotho"}, ["ZAF"]),
    ("ESH", "Western Sahara", "Sahrawi Arab Democratic Republic", ["El Aaiún"], "Africa", "Northern Africa", 597339, "eh", [".eh"], {"MAD": ("Moroccan dirham", "د.م."), "DZD": ("Algerian dinar", "د.ج")}, {"ber": "Berber", "has": "Hassaniya", "spa": "Spanish"}, ["DZA", "MRT", "MAR"]),
    ("GNQ", "Equatorial Guinea", "Republic of Equatorial Guinea", ["Malabo"], "Africa", "Middle Africa", 1402985, "gq", [".gq"], {"XAF": ("Central African CFA franc", "FCFA")}, {"fra": "French", "por": "Portuguese", "spa": "Spanish"}, ["CMR", "GAB"]),
    ("MUS", "Mauritius", "Republic of Mauritius", ["Port Louis"], "Africa", "Eastern Africa", 1265740, "mu", [".mu"], {"MUR": ("Mauritian rupee", "₨")}, {"mfe": "Mauritian Creole", "eng": "English", "fra": "French"}, []),
    ("SWZ", "Eswatini", "Kingdom of Eswatini", ["Mbabane"], "Africa", "Southern Africa", 1160164, "sz", [".sz"], {"SZL": ("Lilangeni", "L"), "ZAR": ("South African rand", "R")}, {"eng": "English", "ssw": "Swati"}, ["MOZ", "ZAF"]),
    ("DJI", "Djibouti", "Republic of Djibouti", ["Djibouti"], "Africa", "Eastern Africa", 988002, "dj", [".dj"], {"DJF": ("Djiboutian franc", "Fdj")}, {"ara": "Arabic", "fra": "French"}, ["ERI", "ETH", "SOM"]),
    ("COM", "Comoros", "Union of the Comoros", ["Moroni"], "Africa", "Eastern Africa", 869595, "km", [".km"], {"KMF": ("Comorian franc", "CF")}, {"ara": "Arabic", "fra": "French", "zdj": "Comorian"}, []),
    ("CPV", "Cape Verde", "Republic of Cabo Verde", ["Praia"], "Africa", "Western Africa", 555988, "cv", [".cv"], {"CVE": ("Cape Verdean escudo", "Esc")}, {"por": "Portuguese"}, []),
    ("MYT", "Mayotte", "Department of Mayotte", ["Mamoudzou"], "Africa", "Eastern Africa", 279471, "yt", [".yt"], {"EUR": ("Euro", "€")}, {"fra": "French"}, []),
    ("REU", "Réunion", "Réunion Island", ["Saint-Denis"], "Africa", "Eastern Africa", 859959, "re", [".re"], {"EUR": ("Euro", "€")}, {"fra": "French"}, []),
    ("STP", "São Tomé and Príncipe", "Democratic Republic of São Tomé and Príncipe", ["São Tomé"], "Africa", "Middle Africa", 219161, "st", [".st"], {"STN": ("São Tomé and Príncipe dobra", "Db")}, {"por": "Portuguese"}, []),
    ("SYC", "Seychelles", "Republic of Seychelles", ["Victoria"], "Africa", "Eastern Africa", 98462, "sc", [".sc"], {"SCR": ("Seychellois rupee", "₨")}, {"crs": "Seychellois Creole", "eng": "English", "fra": "French"}, []),
    ("SHN", "Saint Helena, Ascension and Tristan da Cunha", "Saint Helena, Ascension and Tristan da Cunha", ["Jamestown"], "Africa", "Western Africa", 5314, "sh", [".sh"], {"SHP": ("Saint Helena pound", "£")}, {"eng": "English"}, []),
    ("LBY", "Libya", "State of Libya", ["Tripoli"], "Africa", "Northern Africa", 6871287, "ly", [".ly"], {"LYD": ("Libyan dinar", "ل.د")}, {"ara": "Arabic"}, ["DZA", "TCD", "EGY", "NER", "SDN", "TUN"]),
    ("UGA", "Uganda", "Republic of Uganda", ["Kampala"], "Africa", "Eastern Africa", 45741000, "ug", [".ug"], {"UGX": ("Ugandan shilling", "USh")}, {"eng": "English", "swa": "Swahili"}, ["COD", "KEN", "RWA", "SSD", "TZA"]),
    ("KEN", "Kenya", "Republic of Kenya", ["Nairobi"], "Africa", "Eastern Africa", 53771300, "ke", [".ke"], {"KES": ("Kenyan shilling", "KSh")}, {"eng": "English", "swa": "Swahili"}, ["ETH", "SOM", "SSD", "TZA", "UGA"]),
    ("GAB", "Gabon", "Gabonese Republic", ["Libreville"], "Africa", "Middle Africa", 2225728, "ga", [".ga"], {"XAF": ("Central African CFA franc", "FCFA")}, {"fra": "French"}, ["CMR", "COG", "GNQ"]),

    # Oceania
    ("AUS", "Australia", "Commonwealth of Australia", ["Canberra"], "Oceania", "Australia and New Zealand", 25687041, "au", [".au"], {"AUD": ("Australian dollar", "$")}, {"eng": "English"}, []),
    ("NZL", "New Zealand", "New Zealand", ["Wellington"], "Oceania", "Australia and New Zealand", 5084300, "nz", [".nz"], {"NZD": ("New Zealand dollar", "$")}, {"eng": "English", "mri": "Māori", "nzs": "New Zealand Sign Language"}, []),
    ("PNG", "Papua New Guinea", "Independent State of Papua New Guinea", ["Port Moresby"], "Oceania", "Melanesia", 8935094, "pg", [".pg"], {"PGK": ("Papua New Guinean kina", "K")}, {"eng": "English", "hmo": "Hiri Motu", "tpi": "Tok Pisin"}, ["IDN"]),
    ("FJI", "Fiji", "Republic of Fiji", ["Suva"], "Oceania", "Melanesia", 896444, "fj", [".fj"], {"FJD": ("Fijian dollar", "$")}, {"eng": "English", "fij": "Fijian", "hif": "Fiji Hindi"}, []),
    ("SLB", "Solomon Islands", "Solomon Islands", ["Honiara"], "Oceania", "Melanesia", 686878, "sb", [".sb"], {"SBD": ("Solomon Islands dollar", "$")}, {"eng": "English"}, []),
    ("VUT", "Vanuatu", "Republic of Vanuatu", ["Port Vila"], "Oceania", "Melanesia", 307150, "vu", [".vu"], {"VUV": ("Vanuatu vatu", "VT")}, {"bis": "Bislama", "eng": "English", "fra": "French"}, []),
    ("WSM", "Samoa", "Independent State of Samoa", ["Apia"], "Oceania", "Polynesia", 198410, "ws", [".ws"], {"WST": ("Samoan tālā", "T")}, {"eng": "English", "smo": "Samoan"}, []),
    ("TON", "Tonga", "Kingdom of Tonga", ["Nuku'alofa"], "Oceania", "Polynesia", 105697, "to", [".to"], {"TOP": ("Tongan paʻanga", "T$")}, {"eng": "English", "ton": "Tongan"}, []),
    ("FSM", "Micronesia", "Federated States of Micronesia", ["Palikir"], "Oceania", "Micronesia", 115021, "fm", [".fm"], {"USD": ("United States dollar", "$")}, {"eng": "English"}, []),
    ("PLW", "Palau", "Republic of Palau", ["Ngerulmud"], "Oceania", "Micronesia", 18092, "pw", [".pw"], {"USD": ("United States dollar", "$")}, {"eng": "English", "pau": "Palauan"}, []),
    ("MHL", "Marshall Islands", "Republic of the Marshall Islands", ["Majuro"], "Oceania", "Micronesia", 59194, "mh", [".mh"], {"USD": ("United States dollar", "$")}, {"eng": "English", "mah": "Marshallese"}, []),
    ("NRU", "Nauru", "Republic of Nauru", ["Yaren"], "Oceania", "Micronesia", 10834, "nr", [".nr"], {"AUD": ("Australian dollar", "$")}, {"eng": "English", "nau": "Nauru"}, []),
    ("KIR", "Kiribati", "Independent and Sovereign Republic of Kiribati", ["South Tarawa"], "Oceania", "Micronesia", 119446, "ki", [".ki"], {"AUD": ("Australian dollar", "$"), "KID": ("Kiribati dollar", "$")}, {"eng": "English", "gil": "Gilbertese"}, []),
    ("TUV", "Tuvalu", "Tuvalu", ["Funafuti"], "Oceania", "Polynesia", 11792, "tv", [".tv"], {"AUD": ("Australian dollar", "$"), "TVD": ("Tuvaluan dollar", "$")}, {"eng": "English", "tvl": "Tuvaluan"}, []),
    ("GUM", "Guam", "Guam", ["Hagåtña"], "Oceania", "Micronesia", 168783, "gu", [".gu"], {"USD": ("United States dollar", "$")}, {"cha": "Chamorro", "eng": "English"}, []),
    ("MNP", "Northern Mariana Islands", "Commonwealth of the Northern Mariana Islands", ["Saipan"], "Oceania", "Micronesia", 57557, "mp", [".mp"], {"USD": ("United States dollar", "$")}, {"cal": "Carolinian", "cha": "Chamorro", "eng": "English"}, []),
    ("ASM", "American Samoa", "American Samoa", ["Pago Pago"], "Oceania", "Polynesia", 55197, "as", [".as"], {"USD": ("United States dollar", "$")}, {"eng": "English", "smo": "Samoan"}, []),
    ("NCL", "New Caledonia", "New Caledonia", ["Nouméa"], "Oceania", "Melanesia", 271960, "nc", [".nc"], {"XPF": ("CFP franc", "₣")}, {"fra": "French"}, []),
    ("PYF", "French Polynesia", "French Polynesia", ["Papeete"], "Oceania", "Polynesia", 280904, "pf", [".pf"], {"XPF": ("CFP franc", "₣")}, {"fra": "French"}, []),
    ("WLF", "Wallis and Futuna", "Territory of the Wallis and Futuna Islands", ["Mata-Utu"], "Oceania", "Polynesia", 11558, "wf", [".wf"], {"XPF": ("CFP franc", "₣")}, {"fra": "French"}, []),
    ("NIU", "Niue", "Niue", ["Alofi"], "Oceania", "Polynesia", 1618, "nu", [".nu"], {"NZD": ("New Zealand dollar", "$")}, {"eng": "English", "niu": "Niuean"}, []),
    ("COK", "Cook Islands", "Cook Islands", ["Avarua"], "Oceania", "Polynesia", 17564, "ck", [".ck"], {"NZD": ("New Zealand dollar", "$"), "CKD": ("Cook Islands dollar", "$")}, {"eng": "English", "rar": "Cook Islands Māori"}, []),
    ("PCN", "Pitcairn Islands", "Pitcairn Group of Islands", ["Adamstown"], "Oceania", "Polynesia", 56, "pn", [".pn"], {"NZD": ("New Zealand dollar", "$")}, {"eng": "English"}, []),
    ("NFK", "Norfolk Island", "Territory of Norfolk Island", ["Kingston"], "Oceania", "Australia and New Zealand", 1734, "nf", [".nf"], {"AUD": ("Australian dollar", "$")}, {"eng": "English", "pih": "Norfuk"}, []),
    ("CXR", "Christmas Island", "Territory of Christmas Island", ["Flying Fish Cove"], "Oceania", "Australia and New Zealand", 1843, "cx", [".cx"], {"AUD": ("Australian dollar", "$")}, {"eng": "English"}, []),
    ("CCK", "Cocos (Keeling) Islands", "Territory of Cocos (Keeling) Islands", ["West Island"], "Oceania", "Australia and New Zealand", 544, "cc", [".cc"], {"AUD": ("Australian dollar", "$")}, {"eng": "English"}, []),
    ("HMD", "Heard Island and McDonald Islands", "Heard Island and McDonald Islands", [], "Oceania", "Australia and New Zealand", 0, "hm", [".hm"], {"AUD": ("Australian dollar", "$")}, {"eng": "English"}, []),
    ("TKL", "Tokelau", "Tokelau", ["Fakaofo"], "Oceania", "Polynesia", 1357, "tk", [".tk"], {"NZD": ("New Zealand dollar", "$")}, {"eng": "English", "tkl": "Tokelauan"}, []),

    # Antarctic / Southern Ocean
    ("ATA", "Antarctica", "Antarctica", [], "Antarctic", "Antarctica", 1000, "aq", [".aq"], {}, {"eng": "English"}, []),
    ("BVT", "Bouvet Island", "Bouvet Island", [], "Antarctic", "Antarctica", 0, "bv", [".bv"], {"NOK": ("Norwegian krone", "kr")}, {"nor": "Norwegian"}, []),
    ("SGS", "South Georgia", "South Georgia and the South Sandwich Islands", ["King Edward Point"], "Antarctic", "Antarctica", 30, "gs", [".gs"], {"GBP": ("Falkland Islands pound", "£")}, {"eng": "English"}, []),
    ("ATF", "French Southern Territories", "Territory of the French Southern and Antarctic Lands", ["Port-aux-Français"], "Antarctic", "Antarctica", 400, "tf", [".tf"], {"EUR": ("Euro", "€")}, {"fra": "French"}, []),
    ("IOT", "British Indian Ocean Territory", "British Indian Ocean Territory", ["Diego Garcia"], "Africa", "Eastern Africa", 3000, "io", [".io"], {"USD": ("United States dollar", "$")}, {"eng": "English"}, []),
]

# Generate full Country objects conforming to PROJECT.md Schema
countries_list = []
cca3_set = set()

for item in raw_countries:
    cca3, common, official, capital, region, subregion, pop, flag_code, tld, raw_curr, raw_lang, borders = item
    
    cca3_set.add(cca3)
    
    first_lang_code = list(raw_lang.keys())[0] if raw_lang else "eng"
    native_name_dict = {
        first_lang_code: {
            "official": official,
            "common": common
        }
    }
    
    currencies_dict = {}
    for c_code, (c_name, c_sym) in raw_curr.items():
        currencies_dict[c_code] = {"name": c_name, "symbol": c_sym}
        
    c_obj = {
        "name": {
            "common": common,
            "official": official,
            "nativeName": native_name_dict
        },
        "cca3": cca3,
        "capital": capital,
        "region": region,
        "subregion": subregion,
        "population": pop,
        "flags": {
            "png": f"https://flagcdn.com/w320/{flag_code}.png",
            "svg": f"https://flagcdn.com/{flag_code}.svg",
            "alt": f"The flag of {common}"
        },
        "tld": tld,
        "currencies": currencies_dict,
        "languages": raw_lang,
        "borders": borders
    }
    countries_list.append(c_obj)

# Sanity check borders to ensure all border CCA3 codes exist in the dataset
for c in countries_list:
    valid_borders = [b for b in c["borders"] if b in cca3_set]
    c["borders"] = valid_borders

os.makedirs("public", exist_ok=True)
output_path = os.path.join("public", "data.json")

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(countries_list, f, indent=2, ensure_ascii=False)

print(f"Successfully generated {len(countries_list)} countries in {output_path}")
